name: gpu-binder
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - notebook
  - soundfile
  - pydub
  - sox
  - pydub
  - soundfile
  - pysox
  - pip
  - pip:
    - numpy
    - matplotlib
    - pandas
    - librosa