name: gpu-binder
channels:
  - conda-forge
  # - pytorch
dependencies:
  - python=3.11  # Python 3.11
  # - pytorch
  # - torchaudio
  # - torchvision
  - ipykernel
  - notebook
  - soundfile
  - pydub
  - sox
  - pydub
  - soundfile
  - pysox
  - pip
  pip:
    - numpy
    - matplotlib
    - pandas
    - librosa