name: gpu-binder
channels:
  - conda-forge
  - defaults # or main
dependencies:
  - python=3.11
  - ipykernel
  - notebook
  - soundfile
  - pydub
  - sox
  - pysox  # If you need the Python bindings for sox
  - pip:
    - numpy
    - matplotlib
    - pandas
    - librosa